### ISSUE TITLE
При добавлении одной реплики в репликасет, в котором была всего одна реплика, в итоге получается репликасет из 3х реплик 

### ISSUE THREAD

**Issue by Kasen** [picodata/genin#104]
Текущая конфигурация:
```yaml
  - name: cfgfetcher
    failure_domains:
      - dc1
    roles:
      - ttq.roles.q_cfg_fetcher
    config:
      memtx_memory: 100217728
```

Новая конфигурация:
```yaml
  - name: cfgfetcher
    replicasets_count: 1
    replication_factor: 2
    failure_domains:
      - dc1
    roles:
      - ttq.roles.q_cfg_fetcher
    config:
      memtx_memory: 100217728
```

Итог:
![IMAGE 2023-03-31 12:03:26](https://user-images.githubusercontent.com/625149/229076478-64922ea9-1d22-4687-8120-b34f60ccb01f.jpg)
