### ISSUE TITLE
Некорректное распределение при нескольких серверах в датацентрах

### ISSUE THREAD

**Issue by avprotsenko** [picodata/genin#134]
Как воспроизвести:
создать `cluster.genin.yml`
```yaml
---
topology:
  - name: router
    replicasets_count: 10
    failure_domains: [routers-1, routers-2]
    roles:
      - app.roles.router
      - failover-coordinator
  - name: storage
    replicasets_count: 10
    replication_factor: 4
    failure_domains: [storages-1, storages-2]
    roles:
      - app.roles.storage
hosts:
  - name: routers-1
    config:
      http_port: 8081
      binary_port: 3031
    hosts:
      - name: router1-1
        hosts:
          - name: c1-rt1
            config:
              address: 192.168.137.3
      - name: routers1-2
        hosts:
          - name: c1-rt2
            config:
              address: 192.168.137.4
  - name: storages-1
    config:
      http_port: 8081
      binary_port: 3031
    hosts:
      - name: storages1-1
        hosts:
          - name: c1-db1
            config:
              address: 192.168.137.5
      - name: storages1-2
        hosts:
          - name: c1-db2
            config:
              address: 192.168.137.6
  - name: routers-2
    config:
      http_port: 8081
      binary_port: 3031
    hosts:
      - name: router2-1
        hosts:
          - name: c2-rt1
            config:
              address: 192.168.137.7
      - name: routers2-2
        hosts:
          - name: c2-rt2
            config:
              address: 192.168.137.8
  - name: storages-2
    config:
      http_port: 8081
      binary_port: 3031
    hosts:
      - name: storages2-1
        hosts:
          - name: c2-db1
            config:
              address: 192.168.137.9
      - name: storages2-2
        hosts:
          - name: c2-db2
            config:
              address: 192.168.137.10
failover:
  mode: disabled
vars:
  ansible_user: vagrant
  ansible_password: vagrant
  cartridge_app_name: app
  cartridge_cluster_cookie: app-cookie
  cartridge_package_path: "../app-0.6.0.x86_64.tar.gz"
  cartridge_bootstrap_vshard: true
```
Выполнить `genin build`. Распределение пройдёт на 4 сервера из 8.
