### ISSUE TITLE
Некорректное удаление роли

### ISSUE THREAD

**Issue by avprotsenko** [picodata/genin#161]
genin 0.6.0

cluster.genin.yml
```yaml
---
vars:
  ansible_user: root
  cartridge_app_name: app
  cartridge_cluster_cookie: cluster_cookie

topology:
  - name: router
    replicasets_count: 2
    failure_domains: [router-1-1, router-2-1]
    roles:
      - app.roles.router
      - failover-coordinator
  - name: storage
    replicasets_count: 1
    replication_factor: 2
    failure_domains: [storage-1-1, storage-2-1]
    roles:
      - app.roles.storage
  - name: consumer
    replicasets_count: 1
    replication_factor: 2
    failure_domains: [router-1-1, router-2-1]
    roles:
      - app.roles.kafka_consume
  - name: consumer_eq
    replicasets_count: 1
    replication_factor: 2
    failure_domains: [router-1-1, router-2-1]
    roles:
      - app.roles.eq_kafka_consume
    config:
      memtx_memory: 1073741824
  - name: audit_publisher
    replicasets_count: 1
    replication_factor: 2
    failure_domains: [router-1-1, router-2-1]
    roles:
      - app.roles.audit_publisher
  - name: dlq_publisher
    replicasets_count: 1
    replication_factor: 2
    failure_domains: [router-1-1, router-2-1]
    roles:
      - app.roles.dlq_publisher
  - name: subscription_status
    replicasets_count: 1
    replication_factor: 2
    failure_domains: [router-1-1, router-2-1]
    roles:
      - app.roles.subscription_status
hosts:
  - name: DC1
    config:
      http_port: 8081
      binary_port: 3031
    hosts:
      - name: router-1-1
        config:
          address: 10.5.1.94
      - name: storage-1-1
        config:
          address: 10.5.1.190
  - name: DC2
    config:
      http_port: 8081
      binary_port: 3031
    hosts:
      - name: router-2-1
        config:
          address: 10.5.1.165
      - name: storage-2-1
        config:
          address: 10.5.1.115
failover:
  mode: disabled
```
Как воспроизвести:
```bash
genin build
```
Удаляем роль `subscription_status` и ещё раз делаем 
```bash
genin build
```
При этом репликасеты `consumer` и `storage` остаются в норме, а все остальные бьёт на 2 репликасета по 1 инстансу.
