### ISSUE TITLE
В некоторых случаях неверно задаётся роль для набора реплик

### ISSUE THREAD

**Issue by Kasen** [picodata/genin#166]
Конфигурация с воспроизведением бага:
```yaml
vars:
  ansible_user: root
  cartridge_app_name: name
  cartridge_cluster_cookie: cookie
  cartridge_package_path: ../package.tar.gz
  cartridge_bootstrap_vshard: true
  cartridge_enable_tarantool_repo: false
  cartridge_install_tarantool_for_tgz: false
  cartridge_data_dir: /var/tarantool/data
  cartridge_app_install_dir: /var/tarantool/share
  cartridge_enable_tarantool_repo: false

topology:
  - name: router
    replicasets_count: 2
    roles:
      - app.roles.router
      - failover-coordinator
    config:
      memtx_memory: 128000000

  - name: storage
    replicasets_count: 2
    replication_factor: 2
    roles:
      - app.roles.storage
    config:
      memtx_memory: 32212254720

  - name: exporter
    replicasets_count: 1
    roles:
      - app.roles.exporter
    config:
      memtx_memory: 512000000

  - name: task_coordinator
    replicasets_count: 1
    roles:
      - app.roles.tasks.coordinator
    config:
      memtx_memory: 1024000000

hosts:
  - name: datacenter-1
    config:
      http_port: 8081
      binary_port: 3031
    hosts:
      - name: name1
        config:
          address: 10.10.10.2
      - name: name2
        config:
          address: 10.10.11.2

failover:
  mode: disabled
```
