### ISSUE TITLE
В репликасетах не указываются все инстансы в разделе host:

### ISSUE THREAD

**Issue by kdy999** [picodata/genin#17]
Прописывается только 1-й, а должны быть все
```yml
     storage-2-replicaset:
       vars:
         replicaset_alias: storage-2
         weight: 100
         failover_priority:
           - storage-2
           - storage-2-replica-1
           - storage-2-replica-2
         roles:
           - app.roles.storage
       hosts:
         storage-2: ~
```

Вот так правильно:
```yml
    storage-1-replicaset:
      vars:
        replicaset_alias: storage-1
        weight: 100
        failover_priority:
          - storage-1
          - storage-1-replica-1
          - storage-1-replica-2
        roles:
          - app.roles.storage
      hosts:
        storage-1: ~
        storage-1-replica-1:
        storage-1-replica-2:
```
[tar_logic_test.genin.yaml.gz](https://github.com/picodata/genin/files/8845873/tar_logic_test.genin.yaml.gz)
