### ISSUE TITLE
Incorrect build

### ISSUE THREAD

**Issue by avprotsenko** [picodata/genin#23]
genin -V
genin 0.3.5

cluster.genin.yml
```yaml
---
instances:
  - name: l-n
    type: custom
    count: 2
    replicas: 0
    weight: 10
    roles:
      - logger
      - notifier
  - name: op-t
    type: custom
    count: 5
    replicas: 0
    weight: 10
    roles:
      - output_processor
      - task_runner
  - name: c-ip
    type: custom
    count: 5
    replicas: 0
    weight: 10
    roles:
      - connector
      - input_processor
      - failover-coordinator
  - name: sch
    type: custom
    count: 2
    replicas: 0
    weight: 10
    roles:
      - scheduler
  - name: storage
    type: storage
    count: 3
    replicas: 2
    weight: 10
    roles:
      - storage
hosts:
  - name: vagr_tdg
    type: datacenter
    ports:
      http: 8081
      binary: 3031
    hosts:
      - name: tdg-1
        ip: 192.168.123.2
      - name: tdg-2
        ip: 192.168.123.3
      - name: tdg-3
        ip: 192.168.123.4
failover:
  mode: stateful
  state_provider: etcd2
  ectd2:
    prefix: cartridge/tdg
    lock_delay: 30
    endpoints:
      - "http://192.168.123.2:2379"
vars:
  ansible_user: vagrant
  ansible_password: vagrant
  cartridge_app_name: tdg
  cartridge_cluster_cookie: myapp-cookie
  cartridge_package_path: ./tdg-1.7.17-0-g2a5b4bd18.rpm
```
After genin build with such topology the _inventory.yaml_ contains wrong topology.
```
+-----------+---------------------+---------------------+---------------------+
| ports     | tdg-1               | tdg-2               | tdg-3               |
+===========+=====================+=====================+=====================+
| 8081/3031 | storage-1           | storage-2           | storage-3           |
+-----------+---------------------+---------------------+---------------------+
| 8081/3031 | storage-2-replica-2 | storage-1-replica-1 | storage-1-replica-2 |
+-----------+---------------------+---------------------+---------------------+
| 8081/3031 | storage-3-replica-1 | storage-3-replica-2 | storage-2-replica-1 |
+-----------+---------------------+---------------------+---------------------+
| 8081/3031 | c-ip-1              | c-ip-2              | c-ip-3              |
+-----------+---------------------+---------------------+---------------------+
| 8081/3031 | c-ip-4              | c-ip-5              | op-t-3              |
+-----------+---------------------+---------------------+---------------------+
| 8081/3031 | l-n-1               | l-n-2               | sch-1               |
+-----------+---------------------+---------------------+---------------------+
| 8081/3031 | op-t-1              | op-t-2              | sch-2               |
+-----------+---------------------+---------------------+---------------------+
| 8081/3031 | op-t-4              | op-t-5              |                     |
+-----------+---------------------+---------------------+---------------------+
```
_sch-1_ and _sch-2_ is placed in different places in _inventory.yaml_. 
```yaml
...
  hosts:
...
    sch-1:
      config:
        advertise_uri: "192.168.123.2:3040"
        http_port: "8090"
    sch-2:
      config:
        advertise_uri: "192.168.123.3:3040"
        http_port: "8090"
...
  children:
...
    sch-1-replicaset:
      vars:
        replicaset_alias: sch-1
        weight: 10
        failover_priority:
          - sch-1
        roles:
          - scheduler
      hosts:
        sch-1: ~
    sch-2-replicaset:
      vars:
        replicaset_alias: sch-2
        weight: 10
        failover_priority:
          - sch-2
        roles:
          - scheduler
      hosts:
        sch-2: ~
...
    tdg-3:
      vars:
        ansible_host: 192.168.123.4
      hosts:
        storage-3: ~
        storage-1-replica-2: ~
        storage-2-replica-1: ~
        c-ip-3: ~
        op-t-3: ~
        sch-1: ~
        sch-2: ~
```
