### ISSUE TITLE
Add replicas to custom type (feature request)

### ISSUE THREAD

**Issue by avprotsenko** [picodata/genin#25]
Replicas count for custom type is needed for TDG. Example:
![image](https://user-images.githubusercontent.com/61589506/175016030-b700deb5-55e3-4717-96ec-76af30208d16.png)
How is works now:
_cluster.genin.yml_
```yaml
...
  - name: sch
    type: custom
    count: 1
    replicas: 1
    weight: 10
    roles:
      - scheduler
...
```
_inventory.yml_
```yaml
...
    sch-1:
      config:
        advertise_uri: "192.168.123.4:3037"
        http_port: "8087"
...
    sch-1-replicaset:
      vars:
        replicaset_alias: sch-1
        weight: 10
        failover_priority:
          - sch-1
        roles:
          - scheduler
      hosts:
        sch-1: ~
```
