### ISSUE TITLE
Failover parameters dont fall to inventory

### ISSUE THREAD

**Issue by avprotsenko** [picodata/genin#26]
How to reproduce:
genin init
```yaml
...
failover:
  mode: Stateful
  state_provider: stateboard
  stateboard_params:
    uri:
      ip: 192.168.16.11
      port: 4401
    password: change_me
...
```
genin build
```yaml
---
all:
  vars:
    ansible_user: root
    ansible_password: change_me
    cartridge_app_name: myapp
    cartridge_cluster_cookie: myapp-cookie
  hosts:

```
