### ISSUE TITLE
Add v2 cluster configuration type

### ISSUE THREAD

**Issue by DmitryTravyan** [picodata/genin#41]
Some of the parameters need to be renamed. This should improve the experience for first-time `genin` users.
```yaml
---
topology: # instances
  - name: storage
    type: storage
    replicaset_count: 1     # count
    replication_factor: 2   # replicas
    weight: 10
    roles:
      - storage
    config:
      memtx_memory: 256M
  - name: router
    type: router
    replicaset_count: 1
    roles:
      - router
      - api
      - failover-coordinator
```
