### ISSUE TITLE
Fix error with http port instead of binary in advertise uri

### ISSUE THREAD

**Issue by DmitryTravyan** [picodata/genin#72]
```yaml  
hosts:
    router-1-1:
      config:
        advertise_uri: "127.0.0.1:8081"
        http_port: "8081"
```
