### ISSUE TITLE
Duplicated replicasets names

### ISSUE THREAD

**Issue by LomakinaAsya** [picodata/genin#84]
Currently genin does not raise an error when yaml contains several replicasets with the same name. In addition it can behave unpredictably. See examples:
```
# genin.cluster.yaml
topology:
  - name: router
    replicasets_count: 1
    roles:
      - router
      - failover-coordinator
  - name: router
    replicasets_count: 1
    roles:
      - router
[... unique storages...]
```
![image](https://user-images.githubusercontent.com/52502005/203854886-32ae9a24-f879-411b-ae95-b36c01499535.png)

```
# genin.cluster.yaml
topology:
  - name: router
    replicasets_count: 1
    roles:
      - router
      - failover-coordinator
  - name: router-2
    replicasets_count: 1
    roles:
      - router
  - name: storage
    replicasets_count: 1
    replication_factor: 1
    roles:
      - storage
  - name: storage-2
    replicasets_count: 1
    replication_factor: 1
    roles:
      - storage
  - name: storage
    replicasets_count: 1
    replication_factor: 1
    roles:
      - storage
[... unique storages...]
```
![image](https://user-images.githubusercontent.com/52502005/203854638-f80456b5-7376-43f7-8042-485176029dcf.png)

The duplicated replicasets can be located at any place of file so I can image that user don't notice that at the result.
