### ISSUE TITLE
Add special placeholders for configuration parameters

### ISSUE THREAD

**Issue by VifleY** [picodata/genin#97]
We want to provide genin templates for our customers with some sort of instruction adapt those to their needs.  
Ex.: we want to provide genin config with general topology description, but `memtx_memory` or other parameters should be specified by the customer.  
Now we are specifying minimal viable values, but customers oftenly forget to replace those with the values they actually need. That leads to confusion and difficulties on release  

The would like to adopt the following workflow:
1) We create some genin configuration
2) We specify parameters, that are needed to be replaced by the customer by some values (placeholders)
3) We add some comments with the specific syntax for that parameters
4) On `genin build` we fail and we shall show user the error, which would describe the necessity of removing such a placeholder, and a special comment that was specified in special comments section

The proposed syntax of the placeholders:
```
my_yaml_var: <<my var>> # <<I hereby recommend to replace that, sir>>
```

The error should be something like that:
```
The placeholder <<my var>> was not replaced!
Check the placeholder description: "I hereby recommend to replace that, sir"
<the location of placeholder in yaml config>
```

At build all the placeholders should be checked and all of the errors have to be shown to user.

Limitations of the first step:
1) Do not support multiline special comments
2) We shall support placeholders only at:
-  config / extra vars sections. I believe that number of instances, their roles, replication factor, rs count and other vital things should be specified. 
- hosts IP's and ports
- the default vars - ex. cartridge_package_path / ansible_user

As the development of such technique, we should create an RFC that would describe the introduction of templating to Genin. That is out of scope of this issue. 

Example of desired genin's config:
```
vars:
  ansible_user: root
  cartridge_app_name: app
  cartridge_cluster_cookie: <<my-cluster-cookie>>
  cartridge_package_path: app.tar.gz    

topology:
  - name: router
    replicasets_count: 2                   
    roles:
      - vshard-router
    config:
      memtx_memory: <<memtx_memory>> # <<that should be a placeholder and we shall see that exact comment in the build error>>
                                     # And i believe that we should not care about multiline comments at the first step
  - name: storage
    replicasets_count: 2                    
    replication_factor: 2                    
                                            
    roles:
      - vshard-storage
      - vshard-router
      - failover-coordinator                
    config:
      memtx_memory: <<memtx_memory>> #<<more comments>>             
      vshard_group: storage

hosts:
  - name: picodata
    config:
      http_port: <<http_starting_range>>      # that comments won't be seen in the error message on build                     
      binary_port: <<binary_starting_range>>  #<<that is a binary starting range>>                       
    hosts:
      - name: dc1                               
        hosts:                                 
          - name: host-1
            config:
              address: <<my host ip>> # <<placeholder can hold spaces>>
```

Any feedback and comments (especially on placeholder syntax) are welcome
